// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"foxcard/internal/biz/card"
	"foxcard/internal/conf"
	"foxcard/internal/data"
	"foxcard/internal/server"
	"foxcard/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	cardRepo := data.NewCardRepo(dataData, logger)
	cardUsecase := card.NewCardUsecase(cardRepo, auth, logger)
	cardService := service.NewCardService(cardUsecase)
	grpcServer := server.NewGRPCServer(confServer, cardService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, cardService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
